%%%%%%% This is an example file
%%%%%%% Jing Feng (jing.feng@noaa.gov), Oct 10, 2022
path_modtran='/project/rrg-yihuang-ad/jfeng93/model/MODTRAN6.0/bin/linux/';  %% please change this line to your own data directory
modtran6_airs_tape5_make_cld_profile(path_modtran,nlyr,z,p,t,q,co2,o3,resolution,fwhm,cloud,v1,v2,angle,iLoc,emis,zt,ts);
%% removes existing tapes
system('rm mlw.chn');
system('rm mlw.plt');
%% calls modtran6 to run
system([path_modtran,'mod6c_cons mlw.tp5']); %% mlw.tp5 is the input file generated by the tape5 maker. mod6c_cons is the executable
%% read outputs
[wavenum, rad] =read_channels('mlw.chn',6);  %% mlw.chn is the outputfile; 6 for specifying the version of modtran.